name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  validate-and-build:
    name: Lint, Typecheck & Build
    runs-on: ubuntu-latest

    env:
      DATABASE_URL: "postgresql://postgres:postgres@localhost:5432/wm_dummy?sslmode=require"
      DIRECT_URL: "postgresql://postgres:postgres@localhost:5432/wm_dummy?sslmode=require"
      NEXTAUTH_SECRET: "ci-dummy-nextauth-secret-key-32chars-min-length"
      NEXTAUTH_URL: "http://localhost:3000"

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js 20.x
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Validate Prisma Schema
        run: npx prisma validate

      - name: Generate Prisma Client
        run: npx prisma generate

      - name: Run ESLint
        run: npm run lint

      - name: Run TypeScript typecheck
        run: npx tsc --noEmit

      - name: Build Next.js application
        run: npm run build
